### ISSUE TITLE
IOCTL_USB_GET_HUB_INFORMATION_EX reports ERROR_INVALID_HANDLE on duplicate device handle.

### ISSUE THREAD

**Issue by R030t1** [MicrosoftDocs/windows-driver-docs-ddi#128]
If a hub is opened a second time without closing the first handle the IOCTL in the title will report that the handle is invalid despite CreateFile succeeding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1266e050-abcb-d9c4-b637-b832e805d05f
* Version Independent ID: 896db7db-4f8a-4159-71c7-f3193ccad507
* Content: [IOCTL_USB_GET_HUB_INFORMATION_EX](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_hub_information_ex)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_hub_information_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_hub_information_ex.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thank you, @R030t1 
@PageWriter-MSFT can you look into this, please?

**Comment by PageWriter-MSFT** [comment]
Hi @R030t1

An app should be able to open multiple handles to the hub device and query the hub by sending IOCTL_USB_GET_HUB_INFORMATION_EX. 

Can you provide information about your usage pattern?

PageWriter

**Comment by R030t1** [comment]
As far as I can tell I reopened the hub without closing the first handle. Adding a CloseHandle call to the code in both functions of [my NTDEV mailing list post](https://www.osronline.com/showthread.cfm?link=289397) solved the issue.

**Comment by PageWriter-MSFT** [comment]
Glad to know that the issue is now solved!

PageWriter

**Comment by R030t1** [comment]
>An app should be able to open multiple handles to the hub device and query the hub by sending IOCTL_USB_GET_HUB_INFORMATION_EX.

If that is the case it's not solved, it can just be worked around by ensuring one handle is kept for the entire application lifetime. This is fairly non-obvious so it would be prudent to add it to the documentation.
